services:
  db:
    image: postgres:18-alpine
    container_name: bookmark-db
    restart: always
    environment:
      POSTGRES_USER: bv_user
      POSTGRES_PASSWORD: bv_pass
      POSTGRES_DB: bv_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      target: dev
    container_name: bookmark-api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:0015@db:5432/mydb?schema=public
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev

volumes:
  pgdata:
